### PR TITLE
fixes launch error in mac

### LINKED ISSUE #483: Error message upon launch for Mac users
From @navdeepsinghkhalsa: I'm not sure at what point this started. It's happening because the `user-preferences.json` file doesn't exist, so we should check to see if the file exists before opening, and create a blank file if it doesn't.

This is in `www/js/store.js`
https://github.com/KhalisFoundation/sttm-desktop/blob/dev/www/js/store.js#L13
Just have to update this to `fs.readFileSync(filePath, { flag: 'w' })`

screen shot 2019-01-22 at 9 37 32 am

### PR DESCRIPTION
**Pull request by inderpreetsingh**
fixes #483

### CODE REVIEW

File: www/js/store.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ function parseDataFile(filePath, defaults) {
   // which will be the case on the first application run.
   // `fs.readFileSync` will return a JSON string which we then parse into a Javascript object
   try {
-    return JSON.parse(fs.readFileSync(filePath));
+    return JSON.parse(fs.readFileSync(filePath, { flag: 'w' }));
```
Comment (tsingh777) [inline www/js/store.js]: is `w` the correct flag? seems like `w+` is what we need according to the docs(https://nodejs.org/api/fs.html#fs_file_system_flags) but i could be wrong.
