### PR TITLE
fix: long spacebar press app break issue

### LINKED ISSUE #1777: 9.1.2 (MacOS) - Unexpected crash on long pressing spacebar in navigation
Steps to reproduce:
- Go to any shabad, navigate using spacebar
- Long press the spacebar, the App crashes right after last pankti in baani

https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/0319607f-b484-4f00-8d80-6dd8db7cc223

### PR DESCRIPTION
**Pull request by theamanjs**
Fix #1777

### CODE REVIEW

File: www/main/navigator/shabad/ShabadContent.jsx [hunk 1]
```diff
@@ -1,3 +1,4 @@
+/* eslint-disable import/no-cycle */
```
Comment (Gauravjeetsingh) [inline www/main/navigator/shabad/ShabadContent.jsx:1]: @theamanjs veerji, why do we need to disable this linting rule? Couldn't find any new import with this PR.

Other than that, looks good to me.

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]

File: www/main/navigator/shabad/ShabadContent.jsx (hunk 1 above)
Comment (theamanjs) [reply www/main/navigator/shabad/ShabadContent.jsx:1]: This is an old issue veerji, this can be done in separate issue https://github.com/KhalisFoundation/sttm-desktop/issues/1794

**Review by Gauravjeetsingh — APPROVED** [review]
