### PR TITLE
Analytics bug

### LINKED ISSUE #1294: Sundar Gutka and Ceremonies Not Loading
Might be because I am on an M1 Mac Mini. Need to investigate, could also be related to the refactor

### PR DESCRIPTION
**Pull request by inderpreetsingh**
Fixes #1294 #1293 

Still testing some things.

### CODE REVIEW

File: analytics.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ class Analytics {
     const useragent = this.store.get('user-agent');
 
     if (process.env.NODE_ENV !== 'development') {
-      if (global.getUserSettings.collectStatistics) {
+      if (this.store.get('userPrefs.app.analytics.collectStatistics')) {
```
Comment (tsingh777) [inline analytics.js:34]: this should be good for now. Let's think of how to deprecate the old store completely.

**Review by tsingh777 — APPROVED** [review]
